"""migrando pedidoProducto

Revision ID: 84a92e446109
Revises: d28cfe3805d9
Create Date: 2023-09-19 11:33:13.472375

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '84a92e446109'
down_revision = 'd28cfe3805d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_pedido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=True),
    sa.Column('direccion_compra', sa.String(length=255), nullable=False),
    sa.Column('direccion_pedido', sa.String(length=255), nullable=False),
    sa.Column('fecha_pedido', sa.Date(), nullable=True),
    sa.Column('estado_pedido', sa.String(length=20), nullable=False),
    sa.Column('metodo_entrega', sa.String(length=20), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['tbl_cliente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_pedido_producto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=True),
    sa.Column('producto_id', sa.Integer(), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pedido_id'], ['tbl_pedido.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['tbl_producto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('pedido')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pedido',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cantidad', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('direccion_compra', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('direccion_pedido', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('fecha_pedido', sa.DATE(), nullable=True),
    sa.Column('estado_pedido', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('metodo_entrega', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('cliente_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['tbl_cliente.id'], name='pedido_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('tbl_pedido_producto')
    op.drop_table('tbl_pedido')
    # ### end Alembic commands ###
