"""migrando pedido

Revision ID: d28cfe3805d9
Revises: 61e444c68131
Create Date: 2023-09-19 10:58:50.365481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd28cfe3805d9'
down_revision = '61e444c68131'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pedido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=True),
    sa.Column('direccion_compra', sa.String(length=255), nullable=False),
    sa.Column('direccion_pedido', sa.String(length=255), nullable=False),
    sa.Column('fecha_pedido', sa.Date(), nullable=True),
    sa.Column('estado_pedido', sa.String(length=20), nullable=False),
    sa.Column('metodo_entrega', sa.String(length=20), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['tbl_cliente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pedido')
    # ### end Alembic commands ###
